/**
 * DataMap models for representing data maps and their components
 */

/**
 * Represents a node in a data map
 */
export interface DataMapNode {
  id: string;
  type: 'database' | 'table' | 'column' | 'process' | 'service' | 'group';
  name: string;
  description?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color?: string;
  icon?: string;
  parentId?: string;
  properties?: Record<string, any>;
  // Data source related properties
  dataSourceId?: number;
  dataSourceType?: string;
  entityId?: string;
  entityType?: string;
}

/**
 * Represents an edge (connection) in a data map
 */
export interface DataMapEdge {
  id: string;
  source: string;
  target: string;
  type: 'dataflow' | 'relationship' | 'dependency';
  label?: string;
  points?: { x: number; y: number }[];
  properties?: Record<string, any>;
  // Lineage related properties
  lineageId?: string;
  lineageType?: string;
}

/**
 * Represents a complete data map
 */
export interface DataMap {
  id: string;
  name: string;
  description?: string;
  nodes: DataMapNode[];
  edges: DataMapEdge[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  version: number;
  // Data source related properties
  dataSourceId?: number;
  isAutogenerated?: boolean;
  lastSyncedAt?: string;
}

/**
 * Represents a template for data maps
 */
export interface DataMapTemplate {
  id: string;
  name: string;
  description?: string;
  previewImage?: string;
  nodeTypes: string[];
  edgeTypes: string[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  isPublic: boolean;
}

/**
 * Represents a data map version history entry
 */
export interface DataMapVersion {
  id: string;
  dataMapId: string;
  version: number;
  changes: string;
  createdAt: string;
  createdBy: string;
  snapshot: DataMap;
}