// Re-export all workflow management hooks
export { useTemplateValidation } from "./useTemplateValidation";
export { useTemplateAnalytics } from "./useTemplateAnalytics";
export { useTemplateRecommendations } from "./useTemplateRecommendations";
export { useTemplatePermissions } from "./useTemplatePermissions";
export { useTemplateAudit } from "./useTemplateAudit";
export { useTemplateBackup } from "./useTemplateBackup";
export { useTemplateSync } from "./useTemplateSync";
export { useTemplateCache } from "./useTemplateCache";
export { useTemplateSearch } from "./useTemplateSearch";
export { useWorkflowManagement } from "../useWorkflowManagement";
