"use client"
import EnhancedEntityLineageView from "./enhanced-entity-lineage-view"

// Enhanced mock lineage data with more realistic relationships and varied timestamps
const enhancedLineageData = {
  entities: [
    {
      id: "1",
      name: "customer_transactions",
      entity_type: "table",
      qualified_name: "production.analytics.customer_transactions",
      data_source_name: "PostgreSQL Production",
      direction: "center",
      depth: 0,
      sensitivity_label: "Medium",
      classifications: ["Financial", "Customer Data"],
      last_updated: "2024-01-25T14:45:00Z",
      row_count: 2456789,
      issues_count: 2,
    },
    {
      id: "10",
      name: "raw_transactions",
      entity_type: "table",
      qualified_name: "staging.raw.raw_transactions",
      data_source_name: "PostgreSQL Staging",
      direction: "upstream",
      depth: 1,
      sensitivity_label: "Low",
      classifications: ["Raw Data"],
      last_updated: "2024-01-20T12:00:00Z",
      row_count: 3000000,
      issues_count: 0,
    },
    {
      id: "11",
      name: "customer_master",
      entity_type: "table",
      qualified_name: "production.master.customer_master",
      data_source_name: "PostgreSQL Production",
      direction: "upstream",
      depth: 1,
      sensitivity_label: "High",
      classifications: ["PII", "Customer Data"],
      last_updated: "2024-01-21T16:30:00Z",
      row_count: 156789,
      issues_count: 1,
    },
    {
      id: "12",
      name: "payment_methods",
      entity_type: "table",
      qualified_name: "production.reference.payment_methods",
      data_source_name: "PostgreSQL Production",
      direction: "upstream",
      depth: 1,
      sensitivity_label: "Low",
      classifications: ["Reference Data"],
      last_updated: "2024-01-19T10:00:00Z",
      row_count: 25,
      issues_count: 0,
    },
    {
      id: "20",
      name: "monthly_revenue_report",
      entity_type: "table",
      qualified_name: "analytics.reports.monthly_revenue_report",
      data_source_name: "Snowflake Analytics",
      direction: "downstream",
      depth: 1,
      sensitivity_label: "Medium",
      classifications: ["Financial", "Reporting"],
      last_updated: "2024-01-26T10:00:00Z",
      row_count: 12000,
      issues_count: 0,
    },
    {
      id: "21",
      name: "customer_analytics_view",
      entity_type: "view",
      qualified_name: "production.views.customer_analytics_view",
      data_source_name: "PostgreSQL Production",
      direction: "downstream",
      depth: 1,
      sensitivity_label: "Medium",
      classifications: ["Analytics", "Customer Data"],
      last_updated: "2024-01-27T08:30:00Z",
      row_count: 500000,
      issues_count: 0,
    },
    {
      id: "22",
      name: "fraud_detection_model",
      entity_type: "model",
      qualified_name: "ml.models.fraud_detection_v2",
      data_source_name: "MLflow",
      direction: "downstream",
      depth: 1,
      sensitivity_label: "High",
      classifications: ["ML Model", "Security"],
      last_updated: "2024-01-28T06:00:00Z",
      row_count: null,
      issues_count: 0,
    },
  ],
  relationships: [
    {
      id: "e1",
      source: "10",
      target: "1",
      label: "ETL Pipeline",
      type: "data_flow",
      animated: true,
      last_updated: "2024-01-20T12:30:00Z",
    },
    {
      id: "e2",
      source: "11",
      target: "1",
      label: "JOIN",
      type: "data_flow",
      animated: true,
      last_updated: "2024-01-21T17:00:00Z",
    },
    {
      id: "e3",
      source: "12",
      target: "1",
      label: "Lookup",
      type: "reference",
      animated: false,
      last_updated: "2024-01-19T10:30:00Z",
    },
    {
      id: "e4",
      source: "1",
      target: "20",
      label: "Aggregation",
      type: "data_flow",
      animated: true,
      last_updated: "2024-01-26T10:30:00Z",
    },
    {
      id: "e5",
      source: "1",
      target: "21",
      label: "View",
      type: "view",
      animated: false,
      last_updated: "2024-01-27T09:00:00Z",
    },
    {
      id: "e6",
      source: "1",
      target: "22",
      label: "Feature Engineering",
      type: "ml_pipeline",
      animated: true,
      last_updated: "2024-01-28T06:30:00Z",
    },
  ],
}

interface EntityLineageViewProps {
  entityId: number
  entityType: string
  onEntityClick?: (entityId: number, entityType: string) => void
}

export default function EntityLineageView({ entityId, entityType, onEntityClick }: EntityLineageViewProps) {
  // Use the enhanced lineage view component
  return <EnhancedEntityLineageView entityId={entityId} entityType={entityType} onEntityClick={onEntityClick} />
}
