flowchart TB
  classDef svc fill:#e5e7eb,stroke:#111827,color:#111827
  AUTH_RBAC[AUTH_RBAC]
  DATA_SOURCES[DATA_SOURCES]
  SCANS[SCANS]
  CLASSIFICATION[CLASSIFICATION]
  CATALOG[CATALOG]
  COMPLIANCE[COMPLIANCE]
  RACINE[RACINE]
  AUTH_RBAC --> SCANS
  AUTH_RBAC --> RACINE
  AUTH_RBAC --> DATA_SOURCES
  RACINE --> AUTH_RBAC
  RACINE --> SCANS
  COMPLIANCE --> AUTH_RBAC
  COMPLIANCE --> RACINE
  RACINE --> CATALOG
  CATALOG --> RACINE
  COMPLIANCE --> CATALOG
  SCANS --> AUTH_RBAC
  SCANS --> RACINE
  CATALOG --> DATA_SOURCES
  CATALOG --> SCANS
  CATALOG --> COMPLIANCE
  SCANS --> CATALOG
  CATALOG --> CLASSIFICATION
  CLASSIFICATION --> COMPLIANCE
  CLASSIFICATION --> SCANS
  CLASSIFICATION --> DATA_SOURCES
  CLASSIFICATION --> CATALOG
  DATA_SOURCES --> CLASSIFICATION
  SCANS --> CLASSIFICATION
  SCANS --> COMPLIANCE
  COMPLIANCE --> SCANS
  COMPLIANCE --> DATA_SOURCES
  DATA_SOURCES --> SCANS
  DATA_SOURCES --> COMPLIANCE
  DATA_SOURCES --> CATALOG
  SCANS --> DATA_SOURCES
  RACINE --> DATA_SOURCES
  RACINE --> COMPLIANCE
  DATA_SOURCES --> RACINE
  DATA_SOURCES --> AUTH_RBAC
